### ISSUE TITLE
Italic placeholder on Android

### ISSUE THREAD

**Issue by BOBODDY** [FormsCommunityToolkit/Effects#24]
I've been looking into applying italic effects to the hint text on Android. It seems the font used for the hint isn't exposed and is just set to whatever the regular text's font is. I found [this](http://stackoverflow.com/a/34808566) StackOverflow answer that finds the Layout using reflection and sets the hint font independently, but it's native and I'm not sure if it's something that can be converted to Xamarin.Android.

Thoughts?

**Comment by Depechie** [comment]
Not tried it myself, but pretty sure that if it is only doable low level, we would not get hold of it on effect level :/

**Comment by BOBODDY** [comment]
Looks like you can use reflection to get all the members of a class. I can do more testing later. If it does work, would you guys want it or is it too much of a hack?

**Comment by Depechie** [comment]
Good question, I would assume we would like effects to be equal on each platform ( if possible ), no matter how it is achieved - as long as it is in the boundaries of an effect.
But of course if the this requires a lot of reflection, we need to validate the PR on performance wise I guess...

Anyhow, don't hold back, all PR's will be judged :)

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#10
