### ISSUE TITLE
Feature Request: Autocompletition Effect

### ISSUE THREAD

**Issue by Emasoft** [FormsCommunityToolkit/Effects#28]
An Autocompletition Effect like this one from Whatsapp would be very useful.

![whatsapp-broadcast-282x500](https://cloud.githubusercontent.com/assets/713559/21280382/eeeb5674-c3e5-11e6-86b5-55cae913fd42.png)
![whatsapp-broadcast-img-preview](https://cloud.githubusercontent.com/assets/713559/21280475/784bde7a-c3e6-11e6-91a4-d06eae940efa.jpg)

It should be able to:
- Pull up the textfield to the top of the view (even if the textfield is at the bottom of the page)
- Display a floating menu area of variable height just below the textfield and above the keyboard
- Drop a shadow below the menu
- Populate the menu with a list of elements from an item source List, and using a XAML custom cellview template, or directly from a remote (i.e. Google) data provider
- Display only the elements containing (anywhere, not only at the beginning) the keyword or the letters typed, and filtering the list as we type
- Le the user scroll the list with a drag gesture if the list is bigger than the space between the textfield and the keyboard. A small vertical scroll bar at the right should appear while we scroll as an hint of the remaining space to scroll to reach the bottom.
- Highlight the letters that we've typed in the text of all results in bold and with a customizable color
- Tapping an item should copy the tapped item content in the textfield and close the menu.
- The autocompletition menu should preserve the state when the device is rotated in landscape

**Comment by acaliaro** [comment]
I think this request is too complex to be an effect

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#11
