### ISSUE TITLE
Progress bar colors

### ISSUE THREAD

**Issue by jimbobbennett** [FormsCommunityToolkit/Effects#38]
## Feature Request:
Add a new effect to colour progress bars

**Comment by Depechie** [comment]
Just wondering if this is at all possible with only an effect... cfr. https://forums.xamarin.com/discussion/28894/progressbar-color-in-xamarin-forms

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#16
