### ISSUE TITLE
Remove the readme_first.txt

### ISSUE THREAD

**Issue by jimbobbennett** [FormsCommunityToolkit/Effects#41]
## Feature Request:
Can we remove the readme_first.txt file please. Every time Paket installs this package in an app this file reappears.

**Comment by jamesmontemagno** [comment]
That is the idea and I personally really like it to give setup information like they need to install into all projects. If we don't have anything of importance then I guess we can remove it. Usually I like to also point to docs. Usually helps with first run. I could be wrong, let me know.

**Comment by jimbobbennett** [comment]
Actually closing this - it seems it was paket installing a different file into the project when using it to install this nuget. Weird, apologies!
