### ISSUE TITLE
Failed to resolve assembly on Android

### ISSUE THREAD

**Issue by MuhammadRashid** [FormsCommunityToolkit/Effects#47]
Getting following exception when run on Android: 
Failed to resolve assembly: 'FormsCommunityToolkit.Effects, Culture=neutral, PublicKeyToken=null' (ThinkTime.Droid)

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

## Feature Request:
Please fill in what you would like

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#18
