### ISSUE TITLE
Renaming effects - alignment

### ISSUE THREAD

**Issue by Depechie** [FormsCommunityToolkit/Effects#48]
We are looking to rename the current effects, to streamline the naming.
But we are a bit stuck with the current proposal!

Proposal:
Current name : public class CapitalizeKeyboardEffect : RoutingEffect
New name : public class EntryCapitalizeKeyboard : RoutingEffect
So prefix the control it targets and loose the suffix Effect

But if we uphold this, we get in trouble with the static classes that are needed for adding dependency properties to pass through to the actual RoutingEffect.

Problem:
public static class ChangeColorEffect with tandem class > public class ChangeColorSwitchEffect : RoutingEffect ( https://github.com/FormsCommunityToolkit/Effects/blob/dev/src/Effects/ChangeColorEffect.cs )
public static class ChangePickerColorEffect with tandem class > public class ChangeColorPickerEffect : RoutingEffect ( https://github.com/FormsCommunityToolkit/Effects/blob/dev/src/Effects/ChangePickerColorEffect.cs )

How do we rename these? ChangeColorEffect would become SwitchChangeColor, but what would ChangeColorSwitchEffect be then?
Same with the picker class...

Suggestions?

**Comment by jamesmontemagno** [comment]
I think we should just follow the documentation perhaps?

https://developer.xamarin.com/guides/xamarin-forms/effects/passing-parameters/attached-properties/

So:
* CapitalizeKeyboardEffect
* EntryCapitalizeKeyboardEffect : RoutingEffect
* EntryCapitalizeKeyboardEffect  : PlatformEffect

I think looking at the docs we just keep the Effect at the end. I think it is okay.

**Comment by Depechie** [comment]
That is a good suggestion indeed, but not enough in our scenario!
Problem lies also in the fact that we created 2 change color effects! One for a switch and one for a picker.
So if we follow the ruling both current static classes for the attached properties wouldget the same name, BUT with different properties :/

So we need to do something about that too.

**Comment by jamesmontemagno** [comment]
Ahhhhhh I see now. Interesting.

**Comment by jamesmontemagno** [comment]
Soooooo

* SwitchChangeColor
* SwitchChangeColorEffect : RoutingEffect
* SwitchChangeColorEffect : PlatformEffect

How is that?

**Comment by Depechie** [comment]
I like this!

**Comment by jamesmontemagno** [comment]
Do it! I think we need to do it in the main line though.

**Comment by Depechie** [comment]
Yep... will look at it this week!

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#19
