### ISSUE TITLE
Adding Binding to TextColor or Text on label using CustomFontEffect breaks on iOS

### ISSUE THREAD

**Issue by mikescott8** [FormsCommunityToolkit/Effects#49]
### NOTES:
**- Only on iOS**
**- note sure if this is issue with the effect or the way effects are implemented in Xamarin**

## Bug 
Binding TextColor or Text on a label that is using the effect causes the label to not display the custom font anymore.

Version Number of Plugin: 
Device Tested On: ipad mini (>10.0)
Simulator Tested On: iOS (10.2)

### Expected Behavior
if I bind TextColor the label should display in said color on change

### Actual Behavior
if I bind TextColor the label loses CutomFontEffect

### Steps to reproduce the Behavior
The sample below shows the issue with binding TextColor but it also breaks if you bind Text on a label using the effect.

Medium and BodyDarkTextColor are app resource dictionary items.
StatusIndicatorTextColor is ViewModel property of type Color

```
<Label x:Name="StatusIndicatorWorks" 
                                    Text="1a> &#xf054;"
                                    VerticalOptions="Center" 
                                    VerticalTextAlignment="Center" 
                                    FontSize="{StaticResource Medium}"
                                    TextColor="{DynamicResource BodyDarkTextColor}"
                                    >
    <Label.Effects>
        <effects:CustomFontEffect FontPath="fontawesome-webfont.ttf" FontFamilyName="FontAwesome"/>
    </Label.Effects>
</Label>
<Label x:Name="StatusIndicatorBreaks" 
                                    Text="1b> &#xf054;"
                                    VerticalOptions="Center" 
                                    VerticalTextAlignment="Center" 
                                    FontSize="{StaticResource Medium}"
                                    TextColor="{Binding StatusIndicatorTextColor}"
                                    >
    <Label.Effects>
        <effects:CustomFontEffect FontPath="fontawesome-webfont.ttf" FontFamilyName="FontAwesome"/>
    </Label.Effects>
</Label>
<Label x:Name="StatusIndicatorWorksWithoutEffect" 
                                    Text="2> &#xf054;"
                                    VerticalOptions="Center" 
                                    VerticalTextAlignment="Center" 
                                    FontSize="{StaticResource Medium}"
                                    TextColor="{Binding StatusIndicatorTextColor}"
                                    >
</Label>
```

**Comment by mikescott8** [comment]
![image](https://cloud.githubusercontent.com/assets/1325022/23521442/43baec28-ff3c-11e6-9c76-0c4929ac014b.png)

**Comment by bartlannoeye** [comment]
Please post on https://github.com/FormsCommunityToolkit/FormsCommunityToolkit, we're closing this repo
