### ISSUE TITLE
Switch don't raise event Toggled

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [FormsCommunityToolkit/Effects#50]
If you set FalseColor and TrueColor of Swich, it won't raise event Toggled or change IsToggle property

## Bug 

Version Number of Plugin: FormsCommunityToolkit.Effects.1.0.0.49-beta
Device Tested On: HTC One M9 (Android 6.0)
Simulator Tested On:

## Feature Request:
Please fill in what you would like

**Comment by Depechie** [comment]
Good catch! Will try to fix this...

**Comment by Depechie** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#31

**Comment by Depechie** [comment]
And fixed too :)

**Comment by xamarindevelopervietnam** [comment]
Cheers!
